apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-aku
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: keys
  hostPath: 
    path: /opt/CKAD00019/data
    type: Directory
