apiVersion: v1
kind: Pod
metadata:
  name: nginx-resources
  namespace: ckad
spec:
  containers:
  - name: nginx
    image: nginx:stable
    resources:
      requests:
        memory: "128Mi"
        cpu: "400m"
