apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
  - name: mycontainer
    image: nginx:stable
    env:
      - name: BEST_VARIABLE
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: key1
