apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler2
  namespace: default
spec:
  restartPolicy: Never
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: pvc-test
  containers:
  - name: pv-recycler
    image: nginx
    volumeMounts:
    - name: vol
      mountPath: "/data"
