apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  capacity:
    storage: 1Gi
  storageClassName: "local"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/zhumalievaakmaanai/data
