apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: logger
  namespace: cka
spec:
  nodeSelector: 
    aim: log
  containers:
  - image: nginx
    name: web-pod
  - image: busybox
    name: logger
    args:
    - tail
    - -f
    - /var/log/input.log
    volumeMounts:
    - name: shared
      mountPath: /var/log
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3 
    readinessProbe:
      httpGet:
        path: /started
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3 
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
  volumes:
  - name: shared
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

