apiVersion: v1
kind: Service
metadata:
  labels:
    app: exam
  name: aku-svc
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 8082
    nodePort: 31235
  selector:
    app: aku-svc
  type: NodePort
