apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ckad-exam
  labels:
    app: aku-app
spec:
  containers:
    - name: my-app
      image: nginx
      command: ['-g daemon off; -q']
      args: ['This is custom argument']
      ports:
      - containerPort: 80
  restartPolicy: Never
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: web
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["nginx"]
    args: ["-g", "daemon off;", "-q"]
    ports:
    - containerPort: 80
