apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ssd
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: disk-for-pv-aku
