apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volumw
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: keys
  hostPath:
    path: /opt/CKAD00014/data
    type: Directory
