apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-2
  namespace: default
spec:
  storageClassName: keys
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
