apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: "standard-rwo"
  volumeName: task-pv-volume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"
