apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
  - name: nginx
    image: nginx:stablie
    env:
    - name: BEST_VARIABLE
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: key1
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: my-storage-app
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    volumeMounts:
    - name: volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: task-pv-claim
